name: check_syntax

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, 3.10, 3.11]
        exclude:
          - os: ubuntu-latest
            python-version: "3.10"

    steps:
    - uses: actions/checkout@v3
    - name: Ustawienie wersji Pythona ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Aktualizacja pip
      run: |
        python -m pip install --upgrade pip
    - name: Instalacja flake8 oraz unittest2
      run: |
        pip install flake8 unittest2
    - name: Display Python Version
      run: |
        python --version
    - name: Run flake8
      run: |
        flake8 .
    - name: Run unittest2
      run: |
        python -m unittest2 discover -v
