name: check_syntax

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: [windows-latest, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]
        exclude:
          - OS: ubuntu-latest
            python-version: "3.10"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade --user pip
      - name: Install flake8
        run: |
          pip install flake8
      - name: Install unittest2
        run: |
          pip install unittest2
      - name: Display Python Version
        run: |
          python --version
      - name: Run flake8
        run: |
          flake8 . --count --show-source --statistics
      - name: Run unittest
        run: |
          python -m unittest2 test.py
